ppServer/backend/dex/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView

from ppServer.decorators import verified_account

from . import views

app_name = 'dex'

urlpatterns = [
    path('', verified_account(TemplateView.as_view(template_name="dex/index.html")), name='index'),

    path('monster/', include('dex.monster.urls')),

    path('geschöpf/', views.GeschöpfIndexView.as_view(), name='geschöpf_index'),
    path('geschöpf/<int:pk>', views.GeschöpfDetailView.as_view(), name='geschöpf_detail'),

    path('para_pflanze/', views.ParaPflanzeIndexView.as_view(), name='para_pflanze_index'),
    path('para_pflanze/<int:pk>', views.ParaPflanzeDetailView.as_view(), name='para_pflanze_detail'),

    path('para_tier/', views.ParaTierIndexView.as_view(), name='para_tier_index'),
    path('para_tier/<int:pk>', views.ParaTierDetailView.as_view(), name='para_tier_detail'),
]

ppServer/backend/ppServer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView, RedirectView
from django.urls import include, path

from debug_toolbar.toolbar import debug_toolbar_urls


class LegalActUpdateRedirectView(RedirectView):
    permanent = True
    query_string = True
    pattern_name = "politics:admin-vote-on-legalAct"

    def get_redirect_url(self, *args, **kwargs):
        url = super().get_redirect_url(kwargs["pk"])
        return url

urlpatterns = [
    # custom admin-update view
    path('admin/politics/legalact/<int:pk>/change/', LegalActUpdateRedirectView.as_view()),

    path('admin/', admin.site.urls),
    path('auth/', include('auth_custom.urls')),
    path('accounts/', include('auth_custom.urls')),

    path('cards/', include('cards.urls')),
    path('changelog/', include('changelog.urls')),
    path('character/campaign/', include('campaign.urls')),
    path('character/export/', include('characterExport.urls')),
    path('character/', include('character.urls')),
    path('chat/', include('chat.urls')),
    path('combat/', include('combat.urls')),
    path('crafting/', include('crafting.urls')),
    path('create/', include('create.urls')),
    path('dex/', include('dex.urls')),
    path('file/', include('fileserver.urls')),
    path('chat2.0/', include('httpChat.urls')),
    path('lerneinheiten/', include('lerneinheiten.urls')),
    path('levelUp/', include('levelUp.urls')),
    path('log/', include('log.urls')),
    path('news/', include('news.urls')),
    path('planner/', include('planner.urls')),
    path('politics/', include('politics.urls')),
    path('polls/', include('polls.urls')),
    path('quiz/', include('quiz.urls')),
    path('service/', include('service.urls')),
    path('shop/', include('shop.urls')),
    path('time_space/', include('time_space.urls')),
    path('todo/', include('todo.urls')),
    path('web_push/', include('webPush.urls')),
    path('wiki/', include('wiki.urls')),

    path('robots.txt', TemplateView.as_view(template_name="base/robots.txt")),
    path('sw.js', TemplateView.as_view(template_name="webPush/service_worker.js", content_type='application/javascript'), name='sw.js'),
    path("prometheus/", include("django_prometheus.urls")),

    path('', include("base.urls")),
]

handler404 = TemplateView.as_view(template_name='base/error_404.html')

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

ppServer/backend/time_space/urls.py
from django.urls import path

from . import views

app_name = 'time_space'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('net/<int:pk>/', views.PlayNetView.as_view(), name='net'),
    path('editNet/<int:pk>/', views.EditNetView.as_view(), name='editNet'),
    path('createNet/', views.EditNetView.as_view(), name='createNet'),
    path('manual/', views.ManualView.as_view(), name='manual'),
]

ppServer/backend/time_space/models.py
from django.db import models


class Level(models.Model):
    class Meta:
        ordering = ['name']
        verbose_name = "Level"
        verbose_name_plural = "Levels"

    name = models.CharField(max_length=200, null=False, blank=False, unique=True)
    width = models.PositiveSmallIntegerField(default=15, null=False, blank=False)
    height = models.PositiveSmallIntegerField(default=6, null=False, blank=False)

    tiles = models.JSONField(default=list)

    def __str__(self):
        return self.name

ppServer/backend/time_space/views.py
import json
from typing import Any, Dict

from django.shortcuts import redirect, reverse
from django.views.generic import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from markdown_view.views import MarkdownView

from ppServer.mixins import SpielleitungOnlyMixin, VerifiedAccountMixin

from .models import *

class IndexView(VerifiedAccountMixin, SpielleitungOnlyMixin, ListView):
	model = Level
	template_name = "time_space/index.html"

	def get_context_data(self, *args, **kwargs):
		return super().get_context_data(*args, **kwargs,
			topic = "Zeituhr",
			plus = "+ Netz",
			plus_url = reverse("time_space:createNet"),
		)


class PlayNetView(VerifiedAccountMixin, SpielleitungOnlyMixin, DetailView):
	model = Level
	template_name = "time_space/net.html"

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context["topic"] = context["object"].name
		context["app_index"] = "Zeituhr"
		context["app_index_url"] = reverse("time_space:index")

		return context


class EditNetView(VerifiedAccountMixin, SpielleitungOnlyMixin, TemplateView):
	template_name = "time_space/editor.html"
	
	def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
		level = Level.objects.get(pk=self.kwargs["pk"]) if "pk" in self.kwargs else None
		return super().get_context_data(**kwargs,
			object = level,
			topic = level.name if level else "Neues Zeitproblem",
			app_index = "Zeituhr",
			app_index_url = reverse("time_space:index")
		)
	
	def post(self, request, *args, **kwargs):
		level_data = {
			"name": request.POST.get("levelName"),
			"width": int(request.POST.get("width")),
			"height": int(request.POST.get("height")),
			"tiles": json.loads(request.POST.get("tiles")),
		}

		id = self.kwargs["pk"] if "pk" in self.kwargs else None
		if id:
			level = Level.objects.filter(id=id).update(**level_data)
		else:
			level = Level.objects.create(**level_data)

		return redirect(reverse("time_space:editNet", args=[level.id]))


class ManualView(VerifiedAccountMixin, SpielleitungOnlyMixin, MarkdownView):
	template_name = "time_space/manual.html"
	file_name='/static/time_space/manual.md'

	def get_context_data(self, *args, **kwargs):
		return super().get_context_data(*args, **kwargs,
			topic = "Manual",
			app_index = "Zeituhr",
			app_index_url = reverse("time_space:index"),
		)

ppServer/backend/time_space/templates/time_space/editor.html
{% extends 'base/headed_main.html' %}
{% load static %}

{% block extra-head %}
    {% if object %}{{ object.tiles|json_script:"game" }}{% endif %}
    <script defer src="{% static 'time_space/js/types.js' %}"></script>
    <script defer src="{% static 'time_space/js/utils.js' %}"></script>
    <script defer src="{% static 'time_space/js/fields.js' %}"></script>
    <script defer src="{% static 'time_space/js/editor/tiles.js' %}"></script>
    <script defer src="{% static 'time_space/js/editor/grid.js' %}"></script>
    <script defer src="{% static 'time_space/js/editor/toolbar.js' %}"></script>
    <script defer src="{% static 'time_space/js/editor/index.js' %}"></script>

    <link href="{% static 'time_space/css/editor.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
    <form id="form" class="container" method="post">
        {% csrf_token %}
        <h1><input placeholder="Level" name="levelName" value="{% if object %}{{ object.name }}{% endif %}" required></h1>


        <main>
            <canvas id="grid"></canvas>

            <div>
                <label>Breite</label>
                <input type="number" min="1" value="{% if object %}{{ object.width }}{% else %}10{% endif %}" name="width" required>
            </div>
            <div>
                <label>Höhe</label>
                <input type="number" min="1" value="{% if object %}{{ object.height }}{% else %}6{% endif %}" name="height" required>
            </div>
        </main>
    
        <aside aria-label="Fields">
            <h2 style="text-align: center">Fields</h2>
            <div id="fields" class="toolbar"></div>
        </aside>
    </form>

    <button type="submit" class="btn btn-lg btn-primary my-4" form="form">Speichern</button>
{% endblock %}

ppServer/backend/time_space/templates/time_space/index.html
{% extends 'base/headed_main.html' %}
{% load static %}

{% block extra-head %}
<link rel="stylesheet" href="{% static 'time_space/css/index.css' %}">
{% endblock %}

{% block main %}
	<a href="{% url 'time_space:manual' %}" class="d-block mb-4">Manual</a>

	{% if object_list|length %}
		<h2>Offene Probleme</h2>
	{% endif %}

	<ul>
		{% for net in object_list %}
		<li class="my-3"><a href="{% url 'time_space:net' net.id %}">
			<b>{{ net.name }}</b>
		</a></li>
		{% empty %}
		<b>Alles ist safe</b>
		{% endfor %}
	</ul>
{% endblock %}

ppServer/backend/time_space/templates/time_space/manual.html
{% extends 'base/headed_main.html' %}
{% load static %}

{% block extra-head %}
<link rel="stylesheet" href="{% static 'time_space/css/manual.css' %}">
{% endblock %}

{% block main %}
    {% if use_highlight_js %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/a11y-light.min.css" integrity="sha512-PW96n2amVglidqEDLPUdjJ0zByhT20poSqWJYZRutR6CP2QH58k96WmorqNnC4QXnosNeqMJM8FR/93isIifDQ==" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js" integrity="sha512-lnOllyZZlRk/gQIyjS3+h+LUy54uyM4aGq2zbGc82KTvBlp/fodSpdh/pywPztpU9zUqHcJr+jP+a1zLa9oCJw==" crossorigin="anonymous"></script>
    {% endif %}

    {% comment %}{{ page_title|safe }}{% endcomment %}

    {% if use_toc %}
        <section id="markdown_view_toc">
            <h3>Table of Contents</h3>
            {{ markdown_toc }}
        </section>
    {% endif %}

    <section id="markdown_view_content">
        {{ markdown_content }}
    </section>

    {% if use_highlight_js %}
        <script>
            hljs.initHighlightingOnLoad();
            document.addEventListener("DOMContentLoaded", () => {
                document.querySelectorAll('.md-content div.toc ul').forEach(tag => tag.classList.add("cta-links"));
                document.querySelectorAll('.md-content div.toc ul li a').forEach(tag => tag.classList.add("default-fa"));
                document.querySelectorAll('.md-content table').forEach(tag => tag.classList.add("table table-bordered table-hover table-striped table-mobile tablesorter tablesorter-default"));
            });
        </script>
    {% endif %}
{% endblock %}

ppServer/backend/time_space/templates/time_space/net.html
{% extends 'base/headed_main.html' %}
{% load static %}
{% block extra-head %}
<script src="{% static 'res/js/axios.min.js' %}" type='text/javascript'></script>
<script src="{% static 'base/js/ajax.js' %}"></script>

{{ object.tiles|json_script:"game" }}
{{ object.width|json_script:"width" }}
{{ object.height|json_script:"height" }}

<script defer src="{% static 'time_space/js/types.js' %}"></script>
<script defer src="{% static 'time_space/js/utils.js' %}"></script>
<script defer src="{% static 'time_space/js/game/logger.js' %}"></script>
<script defer src="{% static 'time_space/js/fields.js' %}"></script>
<script defer src="{% static 'time_space/js/wires.js' %}"></script>
<script defer src="{% static 'time_space/js/gates.js' %}"></script>
<script defer src="{% static 'time_space/js/space_fissures.js' %}"></script>
<script defer src="{% static 'time_space/js/time_fissures.js' %}"></script>
<script defer src="{% static 'time_space/js/anomalies.js' %}"></script>
<script defer src="{% static 'time_space/js/placeholders.js' %}"></script>
<script defer src="{% static 'time_space/js/game/board.js' %}"></script>
<script defer src="{% static 'time_space/js/config_models.js' %}"></script>
<script defer src="{% static 'time_space/js/game/index.js' %}"></script>

<link rel="stylesheet" href="{% static 'time_space/css/net.css' %}">
{% endblock %}

{% block main %}
<section class="non-terminal">

    <p>Runde <span id="rounds">0</span></p>
    
    <main class="canvas-container"><canvas id="grid"></canvas></main>
</section>

<section id="terminal">
    <output class="output"></output>
    <div class="prompt">
        {% csrf_token %}
        <label for="command" aria-label="Command Prompt">></label>
        <input id="command" list="commands" onkeydown="run_round(event, this.value)">
    </div>
</section>

<datalist id="commands">
    <option value="//analyze"></option>
    <option value="//crystallize"></option>
    <option value="//delete"></option>
    <option value="//drag"></option>
    <option value="//drop"></option>
    <option value="//forward"></option>
    <option value="//inject"></option>
    <option value="//naturalize"></option>
    <option value="//normalize"></option>
    <option value="//return"></option>
    <option value="//skip"></option>
    <option value="//bdv"></option>
    <option value="//mdv"></option>
    <option value="//mdbv"></option>

    <option value="/init"></option>
    <option value="/s"></option>
    <option value="/type"></option>
    <option value="/response"></option>
    <option value="/splits"></option>
    <option value="/splitn"></option>
    <option value="/help"></option>
    <option value="/help1"></option>
    <option value="/help2"></option>
</datalist>

<div>
    <b>blockierte Befehle:</b>

    <ul id="blocked-commands"></ul>
</div>
{% endblock %}