ppServer/backend/dex/monster/urls.py
from django.urls import path

from . import views, views_sp

urlpatterns = [
    path('', views.MonsterIndexView.as_view(), name='monster_index'),
    path('<int:pk>', views.MonsterDetailView.as_view(), name='monster_detail'),

    path('attack', views.AttackIndexView.as_view(), name='attack_index'),
    path('type', views.TypeTableView.as_view(), name='type_table'),
    path('fähigkeit', views.MonsterFähigkeitView.as_view(), name='monster_fähigkeit_index'),
    path('status-effekt', views.StatusEffektView.as_view(), name='monster_statuseffekt_index'),

    path('farm', views.MonsterFarmView.as_view(), name='monster_farm'),
    path('farm/<int:pk>', views.MonsterFarmDetailView.as_view(), name='monster_detail_farm'),
    path('farm/<int:pk>/levelup', views.MonsterFarmLevelupView.as_view(), name='monster_farm_levelup'),
    path('team', views.MonsterTeamView.as_view(), name='monster_team'),
    path('team/<int:pk>', views.MonsterTeamDetailView.as_view(), name='monster_team_detail'),
    
    # utils
    path('farm/delete', views.delete_spielermonster, name='spieler_monster_delete'),
    path('farm/<int:pk>/new_attack', views.add_attack_to_spielermonster, name='spieler_monster_add_attack'),
    path('farm/<int:pk>/new_team', views.add_team_to_spielermonster, name='spieler_monster_add_team'),
    path('farm/<int:pk>/set_training', views.set_training_of_spielermonster, name='spieler_monster_set_training'),
    path('farm/<int:pk>/delete_attack', views.delete_attack_from_spielermonster, name='spieler_monster_delete_attack'),
    path('farm/<int:pk>/evolve', views.evolve_spielermonster, name='spieler_monster_evolve'),
    path('team/<int:pk>/new_monster', views.add_monster_to_team, name='monster_team_add_monster'),
    path('team/<int:pk>/delete_monster', views.delete_monster_from_team, name='monster_team_delete_monster'),

    path('attack/proposal', views.AttackProposalView.as_view(), name='attack_proposal'),
    path('attack/proposal/<int:pk>', views.AttackProposalView.as_view(), name='attack_proposal'),
    path('sp/visibility', views_sp.MonsterVisibilityView.as_view(), name='sp_monster_visibility'),
    path('sp/attack_to_monster/<int:pk>', views_sp.AttackToMonsterView.as_view(), name='sp_attack_to_monster'),
    
]

ppServer/backend/dex/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView

from ppServer.decorators import verified_account

from . import views

app_name = 'dex'

urlpatterns = [
    path('', verified_account(TemplateView.as_view(template_name="dex/index.html")), name='index'),

    path('monster/', include('dex.monster.urls')),

    path('geschöpf/', views.GeschöpfIndexView.as_view(), name='geschöpf_index'),
    path('geschöpf/<int:pk>', views.GeschöpfDetailView.as_view(), name='geschöpf_detail'),

    path('para_pflanze/', views.ParaPflanzeIndexView.as_view(), name='para_pflanze_index'),
    path('para_pflanze/<int:pk>', views.ParaPflanzeDetailView.as_view(), name='para_pflanze_detail'),

    path('para_tier/', views.ParaTierIndexView.as_view(), name='para_tier_index'),
    path('para_tier/<int:pk>', views.ParaTierDetailView.as_view(), name='para_tier_detail'),
]

ppServer/backend/ppServer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView, RedirectView
from django.urls import include, path

from debug_toolbar.toolbar import debug_toolbar_urls


class LegalActUpdateRedirectView(RedirectView):
    permanent = True
    query_string = True
    pattern_name = "politics:admin-vote-on-legalAct"

    def get_redirect_url(self, *args, **kwargs):
        url = super().get_redirect_url(kwargs["pk"])
        return url

urlpatterns = [
    # custom admin-update view
    path('admin/politics/legalact/<int:pk>/change/', LegalActUpdateRedirectView.as_view()),

    path('admin/', admin.site.urls),
    path('auth/', include('auth_custom.urls')),
    path('accounts/', include('auth_custom.urls')),

    path('cards/', include('cards.urls')),
    path('changelog/', include('changelog.urls')),
    path('character/campaign/', include('campaign.urls')),
    path('character/export/', include('characterExport.urls')),
    path('character/', include('character.urls')),
    path('chat/', include('chat.urls')),
    path('combat/', include('combat.urls')),
    path('crafting/', include('crafting.urls')),
    path('create/', include('create.urls')),
    path('dex/', include('dex.urls')),
    path('file/', include('fileserver.urls')),
    path('chat2.0/', include('httpChat.urls')),
    path('lerneinheiten/', include('lerneinheiten.urls')),
    path('levelUp/', include('levelUp.urls')),
    path('log/', include('log.urls')),
    path('news/', include('news.urls')),
    path('planner/', include('planner.urls')),
    path('politics/', include('politics.urls')),
    path('polls/', include('polls.urls')),
    path('quiz/', include('quiz.urls')),
    path('service/', include('service.urls')),
    path('shop/', include('shop.urls')),
    path('time_space/', include('time_space.urls')),
    path('todo/', include('todo.urls')),
    path('web_push/', include('webPush.urls')),
    path('wiki/', include('wiki.urls')),

    path('robots.txt', TemplateView.as_view(template_name="base/robots.txt")),
    path('sw.js', TemplateView.as_view(template_name="webPush/service_worker.js", content_type='application/javascript'), name='sw.js'),
    path("prometheus/", include("django_prometheus.urls")),

    path('', include("base.urls")),
]

handler404 = TemplateView.as_view(template_name='base/error_404.html')

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

ppServer/backend/dex/monster/models.py
from math import floor
from random import choice
from typing import Iterable

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Subquery, OuterRef, CharField, F, Value, Q, Count, Case, When
from django.db.models.functions import Coalesce, Concat, Cast
from django.db.models.query import QuerySet
from django.utils.html import format_html

from django_resized import ResizedImageField
from colorfield.fields import ColorField

from character.models import Spieler
from ppServer.utils import ConcatSubquery
from ..models import Dice, upload_and_rename_to_id



###### sub-models #########

class MonsterFähigkeit(models.Model):
    class Meta:
        ordering = ["name"]
        verbose_name = "Fähigkeit"
        verbose_name_plural = "Fähigkeiten"

    name = models.CharField(max_length=256, unique=True)
    description = models.TextField(verbose_name="Beschreibung")

    def __str__(self):
        return self.name


class Typ(models.Model):
    class Meta:
        ordering = ["name"]
        verbose_name = "Typ"
        verbose_name_plural = "Typen"

    color = ColorField(default='#B19071')
    text_color = ColorField(default='#070707')
    icon = ResizedImageField(size=[256, 256], upload_to=upload_and_rename_to_id, blank=True)

    name = models.CharField(max_length=128)

    stark_gegen = models.ManyToManyField("Typ", related_name="stark", related_query_name="stark", blank=True)
    schwach_gegen = models.ManyToManyField("Typ", related_name="schwach", related_query_name="schwach", blank=True)
    trifft_nicht = models.ManyToManyField("Typ", related_name="miss", related_query_name="miss", blank=True)

    def __str__(self):
        return self.name
    
    def tag(self):
        styles = f"color: {self.text_color}; background: {self.color}; font-weight: 500 !important; padding: .3em .5em; display: flex; justify-content: center; align-items: center; gap: .3em; border-radius: 300px; overflow: hidden;"

        if self.icon:
            icon_styles = f"mask-image: url({self.icon.url}); mask-position: center center; mask-repeat: no-repeat; mask-size: contain; -webkit-mask-image: url({self.icon.url}); -webkit-mask-position: center center; -webkit-mask-repeat: no-repeat; -webkit-mask-size: contain; background-color: {self.text_color}; height: 1.2em; aspect-ratio: 1"
            return format_html(f"<div style='{styles}'><span style='{icon_styles}' aria-hidden='true'></span>{self.name}</div>")

        else:
            return format_html(f"<div style='{styles}'>{self.name}</div>")
        
    @classmethod
    def get_type_efficiencies(cls, own_types: Iterable["Typ"]) -> {"is_miss": QuerySet["Typ"], "is_strong": QuerySet["Typ"], "is_weak": QuerySet["Typ"]}:
        context = {}

        # own_types = self.types.all()
        context["is_miss"] = Typ.objects.prefetch_related("trifft_nicht").filter(trifft_nicht__in=own_types).distinct()

        # calc raw values
        context["is_strong"] = Typ.objects.prefetch_related("stark_gegen").exclude(id__in=context["is_miss"]).annotate(
            value = Count(F("stark_gegen"), filter=Q(stark_gegen__in=own_types), distinct=False),
        )
        context["is_weak"] = Typ.objects.prefetch_related("schwach_gegen").exclude(id__in=context["is_miss"]).annotate(
            value = Count(F("schwach_gegen"), filter=Q(schwach_gegen__in=own_types), distinct=False),
        )

        # calc damage factor
        context["is_weak"] = context["is_weak"].annotate(
            counter = Coalesce(Subquery(context["is_strong"].filter(id=OuterRef("id")).values("value")[:1]), 0),
            damage_factor = 1.0 / 2**(F("value") - F("counter"))
        )
        context["is_strong"] = context["is_strong"].annotate(
            counter = Coalesce(Subquery(context["is_weak"].filter(id=OuterRef("id")).values("value")[:1]), 0),
            damage_factor = 1 + (F("value") - F("counter")) * 0.5
        )

        # filter based on opposing efficiency (-> see "keep")
        context["is_strong"] = context["is_strong"].filter(damage_factor__gt=1).order_by("name")
        context["is_weak"] = context["is_weak"].filter(damage_factor__lt=1).order_by("name")

        return context

    @classmethod
    def get_type_efficiencies_reverse(cls, own_types: Iterable["Typ"]) -> {"is_miss": QuerySet["Typ"], "is_strong": QuerySet["Typ"], "is_weak": QuerySet["Typ"]}:
        context = {}

        # own_types = self.types.all()
        context["is_miss"] = Typ.objects.prefetch_related("miss").filter(miss__in=own_types).distinct()

        # calc raw values
        context["is_strong"] = Typ.objects.prefetch_related("stark").exclude(id__in=context["is_miss"]).annotate(
            value = Count(F("stark"), filter=Q(stark__in=own_types), distinct=False),
        )
        context["is_weak"] = Typ.objects.prefetch_related("schwach").exclude(id__in=context["is_miss"]).annotate(
            value = Count(F("schwach"), filter=Q(schwach__in=own_types), distinct=False),
        )

        # calc damage factor
        context["is_weak"] = context["is_weak"].annotate(
            counter = Coalesce(Subquery(context["is_strong"].filter(id=OuterRef("id")).values("value")[:1]), 0),
            damage_factor = 1.0 / 2**(F("value") - F("counter"))
        )
        context["is_strong"] = context["is_strong"].annotate(
            counter = Coalesce(Subquery(context["is_weak"].filter(id=OuterRef("id")).values("value")[:1]), 0),
            damage_factor = 1 + (F("value") - F("counter")) * 0.5
        )

        # filter based on opposing efficiency (-> see "keep")
        context["is_strong"] = context["is_strong"].filter(damage_factor__gt=1).order_by("name")
        context["is_weak"] = context["is_weak"].filter(damage_factor__lt=1).order_by("name")

        return context


class Attacke(models.Model):
    class Meta:
        ordering = ["name"]
        verbose_name = "Attacke"
        verbose_name_plural = "Attacken"

    name = models.CharField(max_length=128, unique=True)
    damage = models.ManyToManyField(Dice, blank=True, verbose_name="Schaden")
    description = models.TextField(verbose_name="Beschreibung")
    types = models.ManyToManyField(Typ, verbose_name="Typen")

    macht_schaden = models.BooleanField(default=False)
    macht_effekt = models.BooleanField(default=False)

    angriff_nahkampf = models.BooleanField(default=False)
    angriff_fernkampf = models.BooleanField(default=False)
    angriff_magie = models.BooleanField(default=False)
    verteidigung_geistig = models.BooleanField(default=False)
    verteidigung_körperlich = models.BooleanField(default=False)

    cost = models.PositiveSmallIntegerField(default=0, validators=[MaxValueValidator(7)], verbose_name="Kosten")

    draft = models.BooleanField(default=False)
    author = models.ForeignKey(Spieler, on_delete=models.SET_NULL, null=True, blank=True)
    monster_feddich = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    class CardManager(models.Manager):

        def load_card(self):
            """ preloads all fields needed for display of monster-listentry """
            return self.prefetch_related("types", "damage")
    objects = CardManager()


class MonsterRang(models.Model):
    class Meta:
        ordering = ["rang"]
        verbose_name = "Monster-Rang"
        verbose_name_plural = "Monster-Ränge"

    rang = models.PositiveSmallIntegerField(unique=True)
    schadensWI = models.ManyToManyField(Dice, blank=True)
    reaktionsbonus = models.PositiveSmallIntegerField(default=0)
    angriffsbonus = models.PositiveSmallIntegerField(default=0)
    attackenpunkte = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return f"Rang {self.rang}"


######## living things ########

class Monster(models.Model):
    class Meta:
        ordering = ["number"]
        verbose_name = "Monster"
        verbose_name_plural = "Monster"

    image = ResizedImageField(size=[1024, 1024], upload_to=upload_and_rename_to_id, blank=True)
    number = models.PositiveSmallIntegerField(unique=True)
    name = models.CharField(max_length=128)
    description = models.TextField(verbose_name="Beschreibung")
    habitat = models.TextField()
    fähigkeiten = models.ManyToManyField(MonsterFähigkeit, blank=True)
    
    wildrang = models.PositiveIntegerField(validators=[MinValueValidator(1)], default=1)
    weight = models.FloatField(validators=[MinValueValidator(0.001)], help_text="in kg", default=1)
    height = models.FloatField(validators=[MinValueValidator(0.001)], help_text="in Metern", default=1)

    base_initiative = models.SmallIntegerField(default=0)
    base_hp = models.SmallIntegerField(default=0)
    base_nahkampf = models.SmallIntegerField(default=0)
    base_fernkampf = models.SmallIntegerField(default=0)
    base_magie = models.SmallIntegerField(default=0)
    base_verteidigung_geistig = models.SmallIntegerField(default=0)
    base_verteidigung_körperlich = models.SmallIntegerField(default=0)

    base_schadensWI = models.ManyToManyField(Dice, blank=True)
    base_attackbonus = models.SmallIntegerField(default=0)
    base_reaktionsbonus = models.SmallIntegerField(default=0)


    alternativeForms = models.ManyToManyField("Monster", related_name="forms", related_query_name="forms", blank=True)
    opposites = models.ManyToManyField("Monster", related_name="opposite", related_query_name="opposite", blank=True)
    evolutionPre = models.ManyToManyField("Monster", related_name="evolution_pre", related_query_name="evolution_pre", blank=True)
    evolutionPost = models.ManyToManyField("Monster", related_name="evolution_post", related_query_name="evolution_post", blank=True)

    types = models.ManyToManyField(Typ, blank=True)
    attacken = models.ManyToManyField(Attacke, blank=True)
    visible = models.ManyToManyField(Spieler, blank=True)

    def __str__(self):
        return f"#{self.number} {self.name}"
    

ppServer/backend/dex/templates/dex/monster/attack_index.html
{% extends 'base/headed_main.html' %}
{% load static %}

{% block extra-head %}
<link rel="stylesheet" href="{% static 'dex/monster/css/attack_index.css' %}">
<script src="{% static 'dex/monster/js/attack-filter.js' %}" defer></script>
{% endblock %}

{% block asides %}
{% include 'dex/monster/attack-filter.html' with types=types all_stats=all_stats %}
{% endblock %}

{% block main %}
<ul class="list-unstyled" id="attack-list">
    {% for obj in object_list %}
    <li class="attack-container">{% include 'dex/monster/attack-listentry.html' with attack=obj include_styles=forloop.first %}</li>
    {% endfor %}
</ul>
{% endblock %}

ppServer/backend/dex/templates/dex/monster/attack_proposal.html
{% extends 'base/headed_main.html' %}
{% load static crispy_forms_tags %}

{% block extra-head %}
<link rel="stylesheet" href="{% static 'dex/monster/css/attack_proposal.css' %}">

<script src="{% static 'dex/monster/js/attack-filter.js' %}" defer></script>
{% endblock %}

{% block main %}
<form method="post">
    <h2 class="mb-4">{% if is_create %}Neue Attacke{% else %}Attacke bearbeiten{% endif %}</h2>

    {% csrf_token %}
    {% crispy form %}

    <button class="btn btn-success mt-4" type="submit">Speichern</button>
</form>

<h2 class="mt-5">Deine offenen Attackenvorschläge</h2>

{% if object_list|length %}
    {% include 'dex/monster/attack-filter.html' with types=types all_stats=all_stats %}
{% endif %}

<ul id="attack-list" class="list-unstyled">
    {% for a in object_list %}
    <li class="attack-container">
        {% include 'dex/monster/attack-listentry.html' with attack=a include_styles=forloop.first %}

        <a href="{% url 'dex:attack_proposal' a.id %}" class="edit-attack-btn btn btn-light">
            <svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" viewBox="0 0 512 512">
                <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2023 Fonticons, Inc.-->
                <path fill="currentColor" d="M362.7 19.3L314.3 67.7 444.3 197.7l48.4-48.4c25-25 25-65.5 0-90.5L453.3 19.3c-25-25-65.5-25-90.5 0zm-71 71L58.6 323.5c-10.4 10.4-18 23.3-22.2 37.4L1 481.2C-1.5 489.7 .8 498.8 7 505s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L421.7 220.3 291.7 90.3z"/>
            </svg>
        </a>
    </li>
    {% empty %}
    - keine -
    {% endfor %}
</ul>

{% if not is_create %}
<a href="{% url 'dex:attack_proposal' %}" class="btn btn-lg btn-light mt-5">Neue Attacke vorschlagen</a>
{% endif %}
{% endblock %}

ppServer/backend/dex/templates/dex/monster/booble.html
<style>
.booble {
    /* --booble-size: 1em; */

    height: var(--booble-size);
    width: var(--booble-size);
    border-radius: 50%;
    box-shadow: calc(var(--booble-size) * 0.1) calc(var(--booble-size) *0.1) calc(var(--booble-size) *0.25) calc(var(--booble-size) *0.1) rgba(var(--bs-dark-rgb), .2);
    background: radial-gradient(circle at 35% 35%, var(--bg-color), #222);
}
.booble--base { --bg-color: hsl(0, 0%, 100%); }
.booble--skilled { --bg-color: hsl(96, 100%, 48%); }
.booble--trained { --bg-color: hsl(302, 100%, 48%); }
</style>

{% with ''|center:amount as range %}
{% for _ in range %}
<div class="booble {{ extra_class }}"></div>
{% endfor %}
{% endwith %}

ppServer/backend/dex/templates/dex/monster/monster-farm-listentry.html
{% extends 'dex/monster/monster-listentry.html' %}

{% block imports %}
{{ block.super }}
<style>
    .monster--own.bg-primary {
        --bs-primary-rgb: 214, 51, 132;
    }
</style>
{% endblock %}
{% block extra_class %}monster--own{% endblock %}
{% block name %}{{ sp_mo.name|default:monster.name }}{% endblock %}
{% block rang %}{{ sp_mo.rang }}{% endblock %}
{% block url %}{% url 'dex:monster_detail_farm' sp_mo.id %}{% endblock %}

ppServer/backend/dex/templates/dex/monster/monster-listentry.html
{% load static %}

{% if include_styles %}
{% block imports %}
<link rel="stylesheet" href="{% static 'dex/monster/css/monster-listentry.css' %}">
<script src="{% static 'dex/monster/js/monster_listentry.js' %}" defer></script>
{% endblock %}
{% endif %}


<a class="monster card bg-primary text-light {% block extra_class %}{% endblock %} {% if spieler not in monster.visible.all %} monster--dummy{% else %}" data-base="{{ monster.basiswertsumme }}" data-rank="{% block rang %}{{ monster.wildrang }}{% endblock %}" href="{% block url %}{% url 'dex:monster_detail' monster.id %}{% endblock %}{% endif %}" id="monster-{{ id|default:monster.id }}">
    <span class="monster__number shadow bg-warning text-dark">#{{ monster.number }}</span>
    <b class="monster__name fs-5">{% if spieler in monster.visible.all %}{% block name %}{{ monster.name }}{% endblock %}{% else %}???{% endif %}</b>
    <span class="monster__img shadow h-100">
        {% if spieler in monster.visible.all and monster.image %}
        <button class="open-modal-btn border-0 w-100 h-100" type="button" data-bs-toggle="modal" data-bs-target="#monster-modal-{{ id|default:monster.id }}" aria-label="Monsterbild im Fullscreen öffnen">
            <img class="object-fit-cover w-100 h-100" src="{{ monster.image.url }}" alt="{{ monster.description }}" loading="lazy">
        </button>
        {% endif %}
    </span>
    <small class="monster__types">
        {% if spieler in monster.visible.all %}
            {% for type in monster.types.all %}{{ type.tag }}{% endfor %}
        {% else %}
        ???
        {% endif %}
    </small>
</a>

{% if spieler in monster.visible.all and monster.image %}
<!-- Modal -->
<div class="modal fade" id="monster-modal-{{ id|default:monster.id }}" tabindex="-1" aria-label="{{ monster.name }} - {{ monster.description }}" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen-sm-down">
        <div class="modal-content">
            <div class="modal-body">
                <img class="img-fluid object-fit-cover" src="{{ monster.image.url }}" alt="{{ monster.description }}" loading="lazy">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Schließen</button>
            </div>
        </div>
    </div>
</div>
{% endif %}

ppServer/backend/dex/templates/dex/monster/monster_farm.html
{% extends 'dex/monster/monster_index.html' %}
{% load static l10n %}

{% block extra-head %}
<link rel="stylesheet" href="{% static 'dex/monster/css/monster_farm.css' %}">
<script src="{% static 'dex/monster/js/monster_farm.js' %}" defer></script>
{% endblock %}

{% block main %}
<ul class="list-unstyled" id="monster-list">
    {% for obj in object_list %}
    <li class="del-btn-container">
      {% include 'dex/monster/monster-farm-listentry.html' with sp_mo=obj monster=obj.monster id=obj.id include_styles=forloop.first %}

      <button type="button" class="del-btn del-btn--monster btn btn-sm btn-danger text-light" data-bs-toggle="modal" data-bs-target="#delMonsterModal" data-monster="{% localize off %}{{ obj.id }}{% endlocalize %}">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
          <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2023 Fonticons, Inc.-->
          <path fill="currentColor" d="M368 128c0 44.4-25.4 83.5-64 106.4V256c0 17.7-14.3 32-32 32H176c-17.7 0-32-14.3-32-32V234.4c-38.6-23-64-62.1-64-106.4C80 57.3 144.5 0 224 0s144 57.3 144 128zM168 176a32 32 0 1 0 0-64 32 32 0 1 0 0 64zm144-32a32 32 0 1 0 -64 0 32 32 0 1 0 64 0zM3.4 273.7c7.9-15.8 27.1-22.2 42.9-14.3L224 348.2l177.7-88.8c15.8-7.9 35-1.5 42.9 14.3s1.5 35-14.3 42.9L295.6 384l134.8 67.4c15.8 7.9 22.2 27.1 14.3 42.9s-27.1 22.2-42.9 14.3L224 419.8 46.3 508.6c-15.8 7.9-35 1.5-42.9-14.3s-1.5-35 14.3-42.9L152.4 384 17.7 316.6C1.9 308.7-4.5 289.5 3.4 273.7z"/>
        </svg>
      </button>
    </li>
    {% endfor %}
</ul>


<!-- Modal -->
<div class="modal fade" id="delMonsterModal" tabindex="-1" aria-labelledby="delMonsterLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="delMonsterLabel">Monster freilassen</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Willst du dein <span id="monster_name"></span> wirklich aus deiner Farm entfernen und freilassen?
      </div>

      <form id="monster_del_form" action="{% url 'dex:spieler_monster_delete' %}" method="post">
        {% csrf_token %}
        <input hidden type="number" name="monster_id">
      </form>

      <div class="modal-footer">
        <button type="submit" class="btn btn-danger" form="monster_del_form">Freilassen</button>
        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Schließen</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

ppServer/backend/dex/templates/dex/monster/monster_fähigkeit_index.html
{% extends 'base/headed_main.html' %}
{% load static dex.join_ids %}

{% block extra-head %}
<link rel="stylesheet" href="{% static 'dex/monster/css/monster_fähigkeit_index.css' %}">
{% endblock %}

{% block main %}
<ul class="list-unstyled" id="fähigkeit-list">
    {% for fähigkeit in object_list %}
    <li>
      <a name="{{ fähigkeit.id }}" class="fähigkeit card" type="button" data-bs-toggle="collapse" data-bs-target="#fähigkeit-description-{{ fähigkeit.id }}" aria-expanded="false" aria-controls="fähigkeit-description-{{ fähigkeit.id }}">
          <b class="fähigkeit__name text-dark shadow">{{ fähigkeit.name }}</b>
          <small class="fähigkeit__teaser px-2 pb-1">{{ fähigkeit.description|truncatechars:40 }}</small>
      </a>
      <div class="fähigkeit-description collapse" id="fähigkeit-description-{{ fähigkeit.id }}">
          <div class="card card-body shadow">
            <i>{{ fähigkeit.description }}</i>
            
            {% if fähigkeit.monster_set.count %}
              <hr>
              <label class="h5" for="monsters-{{ fähigkeit.id }}">Bei Monstern:</label>
              <ul class="list-unstyled" id="monsters-{{ fähigkeit.id }}">
                {% for monster in fähigkeit.monster_set.all %}
                  <li>
                    {% include 'dex/monster/monster-listentry.html' with monster=monster id=fähigkeit.id|join_ids:monster.id include_styles=forloop.first %}
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </div>
      </div>

    </li>
    {% endfor %}
</ul>
{% endblock %}