ppServer/backend/dex/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView

from ppServer.decorators import verified_account

from . import views

app_name = 'dex'

urlpatterns = [
    path('', verified_account(TemplateView.as_view(template_name="dex/index.html")), name='index'),

    path('monster/', include('dex.monster.urls')),

    path('geschöpf/', views.GeschöpfIndexView.as_view(), name='geschöpf_index'),
    path('geschöpf/<int:pk>', views.GeschöpfDetailView.as_view(), name='geschöpf_detail'),

    path('para_pflanze/', views.ParaPflanzeIndexView.as_view(), name='para_pflanze_index'),
    path('para_pflanze/<int:pk>', views.ParaPflanzeDetailView.as_view(), name='para_pflanze_detail'),

    path('para_tier/', views.ParaTierIndexView.as_view(), name='para_tier_index'),
    path('para_tier/<int:pk>', views.ParaTierDetailView.as_view(), name='para_tier_detail'),
]

ppServer/backend/levelUp/urls.py
from django.urls import path

from .views.index import IndexView
from .views.klasse import GenericKlasseView
from .views.attribut import GenericAttributView, deny_MA_MG
from .views.fertigkeit import GenericFertigkeitView
from .views.zauber import GenericZauberView
from .views.personal import GenericPersonalView
from .views.teils import GenericVorteilView, GenericNachteilView
from .views.spF_wF import GenericSpF_wFView
from .views.talent import GenericTalentView
from .views.wesenkraft import GenericWesenkraftView
from .views.affektivität import AffektivitätView
from .views.skilltree import GenericSkilltreeView
from .views.gfs_ability import GenericGfsAbilityView

app_name = 'levelUp'

urlpatterns = [
    path('<int:pk>/', IndexView.as_view(), name='index'),
	path('<int:pk>/klasse/', GenericKlasseView.as_view(), name='klasse'),
	path('<int:pk>/attribute/', GenericAttributView.as_view(), name='attribute'),
	path('<int:pk>/attribute/deny/', deny_MA_MG, name='attribute_deny'),
	path('<int:pk>/fertigkeiten/', GenericFertigkeitView.as_view(), name='fertigkeiten'),
	path('<int:pk>/zauber/', GenericZauberView.as_view(), name='zauber'),
	path('<int:pk>/personal/', GenericPersonalView.as_view(), name='personal'),
	path('<int:pk>/vorteile/', GenericVorteilView.as_view(), name='vorteile'),
	path('<int:pk>/nachteile/', GenericNachteilView.as_view(), name='nachteile'),
	path('<int:pk>/spF_wF/', GenericSpF_wFView.as_view(), name='spF_wF'),
	path('<int:pk>/talent/', GenericTalentView.as_view(), name='talent'),
	path('<int:pk>/wesenkraft/', GenericWesenkraftView.as_view(), name='wesenkraft'),
	path('<int:pk>/affektivität/', AffektivitätView.as_view(), name='affektivität'),
	path('<int:pk>/skilltree/', GenericSkilltreeView.as_view(), name='skilltree'),
	path('<int:pk>/gfs_ability/', GenericGfsAbilityView.as_view(), name='gfs_ability'),
]

ppServer/backend/ppServer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView, RedirectView
from django.urls import include, path

from debug_toolbar.toolbar import debug_toolbar_urls


class LegalActUpdateRedirectView(RedirectView):
    permanent = True
    query_string = True
    pattern_name = "politics:admin-vote-on-legalAct"

    def get_redirect_url(self, *args, **kwargs):
        url = super().get_redirect_url(kwargs["pk"])
        return url

urlpatterns = [
    # custom admin-update view
    path('admin/politics/legalact/<int:pk>/change/', LegalActUpdateRedirectView.as_view()),

    path('admin/', admin.site.urls),
    path('auth/', include('auth_custom.urls')),
    path('accounts/', include('auth_custom.urls')),

    path('cards/', include('cards.urls')),
    path('changelog/', include('changelog.urls')),
    path('character/campaign/', include('campaign.urls')),
    path('character/export/', include('characterExport.urls')),
    path('character/', include('character.urls')),
    path('chat/', include('chat.urls')),
    path('combat/', include('combat.urls')),
    path('crafting/', include('crafting.urls')),
    path('create/', include('create.urls')),
    path('dex/', include('dex.urls')),
    path('file/', include('fileserver.urls')),
    path('chat2.0/', include('httpChat.urls')),
    path('lerneinheiten/', include('lerneinheiten.urls')),
    path('levelUp/', include('levelUp.urls')),
    path('log/', include('log.urls')),
    path('news/', include('news.urls')),
    path('planner/', include('planner.urls')),
    path('politics/', include('politics.urls')),
    path('polls/', include('polls.urls')),
    path('quiz/', include('quiz.urls')),
    path('service/', include('service.urls')),
    path('shop/', include('shop.urls')),
    path('time_space/', include('time_space.urls')),
    path('todo/', include('todo.urls')),
    path('web_push/', include('webPush.urls')),
    path('wiki/', include('wiki.urls')),

    path('robots.txt', TemplateView.as_view(template_name="base/robots.txt")),
    path('sw.js', TemplateView.as_view(template_name="webPush/service_worker.js", content_type='application/javascript'), name='sw.js'),
    path("prometheus/", include("django_prometheus.urls")),

    path('', include("base.urls")),
]

handler404 = TemplateView.as_view(template_name='base/error_404.html')

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

ppServer/backend/shop/urls.py
from django.urls import path, register_converter

from .converter import *
from .views.index import index, review_items, transfer_items, propose_item, shopmodel_list
from .views.buy import BuyView
from .views import list as listViews

app_name = 'shop'
register_converter(get_ModelNameConverter(app_name, shopmodel_list), "model")
register_converter(get_ModelNameConverter(app_name, [m for m in shopmodel_list if m._meta.model_name != "tinker"]), "buyable_model")

urlpatterns = [
    path('', index, name='index'),
    path('review/', review_items, name='review_items'),
    path('transfer-items/', transfer_items, name='transfer_items'),
    path('propose/<model:model>/', propose_item, name="propose"),

    path('all/', listViews.FullShopTableView.as_view(), name='all'),

    path('items/', listViews.ItemTableView.as_view(), name='item_list'),
    path('waffen_werkzeuge/', listViews.WaffenWerkzeugeTableView.as_view(), name='waffen_werkzeuge_list'),
    path('magazine/', listViews.MagazinTableView.as_view(), name='magazin_list'),
    path('pfeile_bolzen/', listViews.PfeilBolzenTableView.as_view(), name='pfeil_bolzen_list'),
    path("schusswaffen", listViews.SchusswaffenTableView.as_view(), name='schusswaffen_list'),
    path('magische_ausrüstung/', listViews.MagischeAusrüstungTableView.as_view(), name='magische_ausrüstung_list'),
    path('rituale_runen/', listViews.RitualeRunenTableView.as_view(), name='rituale_runen_list'),
    path('rüstungen/', listViews.RüstungTableView.as_view(), name='rüstung_list'),
    path('ausruestung_technik/', listViews.AusrüstungTechnikTableView.as_view(), name='ausrüstung_technik_list'),
    path('fahrzeuge/', listViews.FahrzeugTableView.as_view(), name='fahrzeug_list'),
    path('einbauten/', listViews.EinbautenTableView.as_view(), name='einbauten_list'),
    path('zauber/', listViews.ZauberTableView.as_view(), name='zauber_list'),
    path('alchemie/', listViews.AlchemieTableView.as_view(), name='alchemie_list'),
    path('tinker/', listViews.TinkerTableView.as_view(), name='tinker_list'),
    path('begleiter/', listViews.BegleiterTableView.as_view(), name='begleiter_list'),
    path('engelsroboter/', listViews.EngelsroboterTableView.as_view(), name='engelsroboter_list'),

    path('buy_<buyable_model:model>/<int:id>/', BuyView.as_view(), name="buy"),
]

ppServer/backend/wiki/urls.py
from django.urls import path

from . import views

app_name = 'wiki'

urlpatterns = [
    path('', views.index, name='index'),
    path('vorteil/', views.VorteilView.as_view(), name='vorteile'),
    path('nachteil/', views.NachteilView.as_view(), name='nachteile'),
    path('talente/', views.TalentView.as_view(), name='talente'),


    path('klassen/', views.KlasseListView.as_view(), name='klassen'),
    path('klassen/<int:pk>', views.KlasseDetailView.as_view(), name='klasse'),
    path('gfs/', views.GfsView.as_view(), name='gfs'),
    path('wesen/', views.WesenView.as_view(), name='wesen'),
    path('gfs/special-abilities/', views.GfsSpecialAbilities.as_view(), name='gfs-special-abilities'),
    path('gfs/<int:gfs_id>/', views.stufenplan, name='stufenplan'),
    path('persönlichkeiten/', views.PersönlichkeitTableView.as_view(), name='persönlichkeiten'),

    path('spezial/', views.SpezialfertigkeitTableView.as_view(), name='spezial'),
    path('wissen/', views.WissensfertigkeitTableView.as_view(), name='wissen'),
    path('wesenkraft/', views.WesenkraftTableView.as_view(), name='wesenkraft'),

    path('berufe/', views.BerufTableView.as_view(), name='berufe'),
    path('berufe/add', views.BerufAddView.as_view(), name='beruf_add'),
    path('religionen/', views.ReligionTableView.as_view(), name='religionen'),
    path('religionen/add', views.ReligionAddView.as_view(), name='religion_add'),

    path('geburtstage/', views.GeburtstageView.as_view(), name='geburtstage'),

    path('regeln/', views.RuleListView.as_view(), name='rule_index'),
    path('regeln/<int:pk>/', views.RuleDetailView.as_view(), name='rule_detail'),
]

ppServer/backend/levelUp/views/affektivität.py
from django.db.models import Value
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.utils.html import format_html

import django_tables2 as tables

from base.abstract_views import GenericTable
from character.models import Affektivität

from ..decorators import is_erstellung_done
from ..forms import AffektivitätForm
from ..mixins import LevelUpMixin, LevelUpMixin


@method_decorator([is_erstellung_done], name="dispatch")
class AffektivitätView(LevelUpMixin, tables.SingleTableMixin, TemplateView):

    class Table(GenericTable):

        class Meta:
            attrs = GenericTable.Meta.attrs
            model = Affektivität
            fields = ["name", "wert", "notiz"]

        def render_wert(self, value, record):
            id = record.id
            return format_html(f"<input type='number' form='form' name='wert-{id}' value='{value}' min='-200' max='200' class='input form-control'>")

        def render_notiz(self, value, record):
            id = record.id
            value = record.notizen
            return format_html(f"<textarea class='form-control' form='form' name='notizen-{id}'>{value}</textarea>")


    template_name = "levelUp/affektivität.html"
    model = Affektivität

    table_class = Table
    table_pagination = False

    def get_queryset(self):
        return Affektivität.objects.filter(char=self.get_character())\
            .annotate(notiz=Value(1))   # replace later
    
    def get_context_data(self, *args, **kwargs):
        return super().get_context_data(*args, **kwargs,
            table = self.Table(self.get_table_data()),
            form = AffektivitätForm(),
            topic = "Affektivität",
        )

    def post(self, request, *args, **kwargs):
        char = self.get_character()
        method = request.POST.get("method")

        if method == "update":

            # collect values
            wert_ids = {int(key.replace("wert-", "")): int(w) for key, w in request.POST.items() if "wert-" in key and len(w)}
            notizen_ids = {int(key.replace("notizen-", "")): n for key, n in request.POST.items() if "notizen-" in key}

            # test ids
            if len(wert_ids.keys()) != len(notizen_ids.keys()):
                messages.error(request, "Das Format habe ich nicht verstanden. Das waren unterschiedlich viele Werte und Notizen.")
                return redirect(request.build_absolute_uri())

            own_ids = [e.id for e in Affektivität.objects.filter(char=char)]
            for id, wert in wert_ids.items():
                if id not in own_ids or id not in notizen_ids.keys():
                    messages.error(request, "Das Format habe ich nicht verstanden. Die IDs waren durcheinander.")
                    return redirect(request.build_absolute_uri())

            # # apply them to db
            # TODO handle delete

            # update or create
            own_ids = [e.id for e in Affektivität.objects.filter(char=char)]
            for id, wert in wert_ids.items():
                Affektivität.objects.update_or_create(id=id, defaults={"wert": wert, "notizen": notizen_ids[id]})

        if method == "create":
            form = AffektivitätForm(request.POST)
            form.full_clean()
            form.cleaned_data["char"] = char

            # invalid?
            if not form.is_valid():
                messages.error(request, "Nicht valid")
                return redirect(request.build_absolute_uri())

            # add char
            aff = form.save(commit=False)
            aff.char = char
            aff.save()

        # return response
        messages.success(request, "Erfolgreich gespeichert")
        return redirect(request.build_absolute_uri())

ppServer/backend/levelUp/views/gfs_ability.py
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.utils.html import format_html

import django_tables2 as tables

from base.abstract_views import GenericTable
from character.models import GfsAbility, RelGfsAbility

from ..decorators import is_erstellung_done
from ..mixins import LevelUpMixin


@method_decorator([is_erstellung_done], name="dispatch")
class GenericGfsAbilityView(LevelUpMixin, tables.SingleTableMixin, TemplateView):

    class Table(GenericTable):

        class Meta:
            attrs = GenericTable.Meta.attrs
            model = GfsAbility
            fields = ["name", "beschreibung", "notiz"]

        notiz = tables.Column(verbose_name="Notizen")

        def render_notiz(self, value, record):
            return format_html(f"<textarea form='form' name='{record['id']}' required>{record['notizen']}</textarea>")


    template_name = "levelUp/gfs_ability.html"
    topic = "Gfs-Fähigkeiten"
    model = GfsAbility

    table_class = Table
    table_pagination = False

    def get_queryset(self):
        char = self.get_character()

        return [{"id": entry.id, "name": entry.ability.name, "beschreibung": entry.ability.beschreibung, "notizen": entry.notizen if entry.notizen else "", "notiz": "---" if entry.ability.has_choice else None} for entry in RelGfsAbility.objects.prefetch_related("ability").filter(char=char)]

    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs,
            table = self.Table(self.get_table_data())
        )
        # create or override -> don't cause 'get_context_data() got multiple values for keyword argument 'char''
        context["char"] = self.get_character()
        return context

    def post(self, request, *args, **kwargs):
        char = self.get_character()

        relabiliy_ids = set([int(st) for st in request.POST.keys() if st.isnumeric()])

        rels = []
        for rel in RelGfsAbility.objects.filter(id__in=relabiliy_ids, char=char):
            rel.notizen = request.POST.get(str(rel.id))
            rels.append(rel)

        RelGfsAbility.objects.bulk_update(rels, ["notizen"])

        # return response
        messages.success(request, "Erfolgreich gespeichert")
        return redirect(request.build_absolute_uri())

ppServer/backend/levelUp/views/personal.py
from django.contrib import messages
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator

from character.models import *

from ..decorators import is_erstellung_done
from ..forms import PersonalForm
from ..mixins import LevelUpMixin


@method_decorator([is_erstellung_done], name="dispatch")
class GenericPersonalView(LevelUpMixin, TemplateView):
    template_name = "levelUp/personal.html"

    def get_context_data(self, *args, **kwargs):
        char = self.get_character()
        return super().get_context_data(*args, **kwargs, form = PersonalForm(instance=char), topic = "Persönliches")


    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        char = self.get_character()

        form = PersonalForm(request.POST, request.FILES, instance=char)
        form.full_clean()
        if form.is_valid():
            form.save()
            messages.success(request, "Erfolgreich gespeichert")

        return redirect(request.build_absolute_uri())

ppServer/backend/levelUp/templates/levelUp/_number_input.html
{% load levelUp.getattr l10n %}

<div>
    {% localize off %}

    <!-- input -->
    <input
        type="number"
        min="0"
        max="{{ record|getattribute:max_field }}"
        
        class="{{ base_class }}-input"
        data-id="{{ record|getattribute:dataset_id }}"
        
        form="form"
        name="{{ base_name }}-{{ record|getattribute:dataset_id }}"
        value="{{ record|getattribute:input_field|default:0 }}"

        style="max-width:100px"
        {% if record|getattribute:disabled %}disabled{% endif %}
    >

    <!-- + fixwert -->
    {% if record|getattribute:add_field %}
    +<span data-id="{{ record|getattribute:dataset_id }}" class="{{ base_class }}-fix">{{ record|getattribute:add_field }}</span>
    {% endif %}

    <!-- (+ bonus) -->
    {% if record|getattribute:bonus_field %}
    (+<span data-id="{{ record|getattribute:dataset_id }}" class="{{ base_class }}-bonus">{{ record|getattribute:bonus_field }})</span>
    {% endif %}

    {{ record|getattribute:text|default:"" }}

    {% endlocalize %}
</div>

ppServer/backend/levelUp/templates/levelUp/_text_input.html
{% load levelUp.getattr l10n %}

<input
    type="text"
    maxlength="{{ maxlength }}"
    class="{{ base_class }}-input"
    data-id="{% localize off %}{{ record|getattribute:dataset_id }}{% endlocalize %}"

    form="form"
    name="{{ base_name }}-{% localize off %}{{ record|getattribute:dataset_id }}{% endlocalize %}"
    value="{% localize off %}{{ value|default:'' }}{% endlocalize %}"
    placeholder="---"

    style="max-width:300px"
>

ppServer/backend/levelUp/templates/levelUp/affektivität.html
{% extends 'base/dynamic-table.html' %}
{% load static levelUp.resources l10n crispy_forms_tags %}
{% block extra-head %}
<style>
    table {
        max-width: 700px;
        margin-inline: auto;
    }

    .input {
        max-width: 100px;
    }
</style>
{% endblock %}

{% block after_table %}
<form id="form" method="post" class="d-flex justify-content-center">
    {% csrf_token %}
    <input type="hidden" name="method" value="update">
    
    <button type="submit" class="btn btn-primary m-2">Speichern</button>
</form>


<form method="post" class="mx-auto my-5" style="max-width: 300px;">
    <h2>Neu</h2>

    {% csrf_token %}
    <input type="hidden" name="method" value="create">
    {% crispy form %}

    <button type="submit" class="btn btn-primary m-2">Neu anlegen</button>
</form>

<a class="btn btn-outline-primary my-2" href="{{ back_url }}">Zurück</a>
{% endblock %}

ppServer/backend/levelUp/templates/levelUp/ap.html
{% extends 'base/dynamic-table.html' %}
{% load static levelUp.resources l10n crispy_forms_tags %}

{% block extra-head %}
<style>
    table, .note {
        max-width: 700px;
        margin-inline: auto;
    }
</style>

{{ INITIAL_AP_PENALTY_AKTUELL|json_script:"INITIAL_AP_PENALTY_AKTUELL" }}
{{ INITIAL_AP_PENALTY_MAX|json_script:"INITIAL_AP_PENALTY_MAX" }}
<script src="{% static 'levelUp/js/ap.js' %}" type="text/javascript"></script>
{% endblock %}

{% block asides %}{{ block.super }}
    {% resources %}<p><b id="ap_pool">{% localize off %}{{ char.ap }}{% endlocalize %}</b> AP</p>{% endresources %}
{% endblock %}

{% block after_table %}
<p class="note mt-4">Den aktuellen Wert zu erhöhen kostet 1 AP, das Maximum 2 AP. Wenn von 0 auf 1 erhöht wird, kostet es noch 1 AP mehr.</p>

<div class="note mt-5">
    <h2>Sonderfall Magie und Managetik</h2>
    <p>s. weitere Vorteile <a class="text-white" href="{% url 'wiki:rule_detail' 13 %}" target="_blank">in den Regeln</a>.</p>

    {% crispy denial_form %}
</div>

<div class="fixed-bottom">
    <form id="form" method="post" class="d-flex justify-content-center sticky-footer">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary attr-submit-btn" disabled>Speichern</button>
        <a class="btn btn-outline-primary mx-2" href="{{ back_url }}">Zurück</a>
    </form>
</div>
{% endblock %}

ppServer/backend/levelUp/templates/levelUp/klasse.html
{% extends 'base/headed_main.html' %}
{% load static levelUp.resources l10n %}

{% block extra-head %}{{ block.super }}
<style>
    :where(#characterResources, .main-container) a {
        --bs-link-color: currentcolor;
        --bs-link-hover-color: currentcolor;

        &:hover { opacity: 0.75; }
    }
    .main-container {
        ul > :not(li) { display: none; }
        .formitem {
            display: grid;
            grid-template-columns: auto 1fr;
            gap: 1em;
        }
        .card {
            width: min(100%, 45ch);

            .card-text p br {
                display: block;
                margin-top: .5em;
            }
        }
        .card-title {
            display: flex;
            flex-direction: row;
            align-items: center;
            justify-content: flex-start;
            gap: .3em;

            .klasse-icon {
                width: 2em;
                aspect-ratio: 1;
            }
        }
    }
</style>

<script type="text/javascript" src="{% static 'levelUp/js/klasse.js' %}" defer></script>
{% endblock %}

{% block asides %}
{% resources %}
    <!-- Resources -->
     {% if missing_stufen > 0 %}
    <p class=" mb-5">{{ missing_stufen }} Stufe{% if missing_stufen != 1 %}n{% endif %}</p>
    {% endif %}

    <a class="text-light d-block" href="{% url 'wiki:klassen' %}" target="_blank">alle Klassen angucken</a>
{% endresources %}
{% endblock %}

{% block main %}
    {% if own_klassen|length == 0 and missing_stufen <= 0 %}
    <p class="h4 mb-3 d-block">Du hast keine Klassen und kannst auch keine wählen.</p>
    {% endif %}

    {% if own_klassen|length > 0 %}
        <h2>Deine Klassen</h2>

        <ul>
            {% for rel in own_klassen %}
            <li class="card text-bg-dark my-4">
                <div class="card-body">
                    <a class="card-title h5" href="{% url 'wiki:klasse' rel.klasse.pk %}" target="_blank">{{ rel.klasse.titel }}</a>
                    <div class="card-subtitle mt-2 mb-3 text-muted">Stufe {{ rel.stufe }}</div>
                    <small class="card-text">
                        <ul>
                            {% if rel.ap %}<li>{{ rel.ap }} AP</li>{% endif %}
                            {% if rel.fp %}<li>{{ rel.fp }} FP</li>{% endif %}
                            {% if rel.fg %}<li>{{ rel.fg }} FG</li>{% endif %}
                            {% if rel.tp %}<li>{{ rel.tp }} TP</li>{% endif %}
                            {% if rel.ip %}<li>{{ rel.ip }} IP</li>{% endif %}
                            {% if rel.zauber %}<li>{{ rel.zauber }} Zauberslots</li>{% endif %}
                            <li>Klassenfähigkeiten:<ul>{{ rel.abilities|safe|linebreaks }}</ul></li>
                        </ul>
                    </small>
                </div>
            </li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if missing_stufen > 0 %}
    <form id="create-form" method="post">
        <h2>Neue Klassenstufen wählen</h2>
        {% csrf_token %}

        <ul class="p-0">
            {% for rel in stufenpläne %}
            <li class="formitem my-4">
                <input type="radio" id="stufenplan-{% localize off %}{{ rel.id }}{% endlocalize %}" name="stufenplan_id" value="{% localize off %}{{ rel.id }}{% endlocalize %}" class="form-check-input" {% if not rel.requirements_met %}disabled{% endif %}>
                <label for="stufenplan-{% localize off %}{{ rel.id }}{% endlocalize %}">
                    <div class="card text-bg-dark{% if not rel.requirements_met %} text-muted{% endif %}">
                        <div class="card-body">
                            <a class="card-title h5" href="{% url 'wiki:klasse' rel.klasse.pk %}" target="_blank">
                                <img src="{% if rel.klasse.icon %}{{ rel.klasse.icon.url }}{% else %}{% static 'res/img/goren_logo.svg' %}{% endif %}" class="klasse-icon" loading="lazy">
                                {{ rel.klasse.titel }} Stufe {{ rel.stufe }}
                            </a>
                            {% if rel.stufe == rel.min_stufe or not rel.requirements_met %}<div class="card-subtitle mt-2 mb-3 text-muted">Voraussetzung: {{ rel.klasse.requirement }}</div>{% endif %}
                            <small class="card-text">
                                {% if rel.stufe == rel.min_stufe %}
                                <ul>
                                    {% for ability in rel.klasse.base_abilities.all %}
                                    <li><b>{{ ability.name }}</b><br>{{ ability.beschreibung }}</li>
                                    {% endfor %}
                                </ul>
                                {% else %}
                                    <ul>
                                        {% if rel.ap %}<li>{{ rel.ap }} AP</li>{% endif %}
                                        {% if rel.fp %}<li>{{ rel.fp }} FP</li>{% endif %}
                                        {% if rel.fg %}<li>{{ rel.fg }} FG</li>{% endif %}
                                        {% if rel.tp %}<li>{{ rel.tp }} TP</li>{% endif %}
                                        {% if rel.ip %}<li>{{ rel.ip }} IP</li>{% endif %}
                                        {% if rel.zauber %}<li>{{ rel.zauber }} Zauberslots</li>{% endif %}
                                        {% if rel.ability %}<li><b>{{ rel.ability.name }}</b>{{ rel.ability.beschreibung|linebreaks }}</li>{% endif %}
                                    </ul>
                                {% endif %}
                            </small>
                        </div>
                    </div>
                </label>
            </li>
            {% endfor %}
        </ul>
    </form>
    {% endif %}

        
    <div class="fixed-bottom">
        <footer class="sticky-footer d-flex justify-content-center">
            <button id="choose-stufe" class="btn btn-primary" form="create-form" disabled>Stufe wählen</button>
            <a class="btn btn-outline-primary mx-2" href="{{ back_url }}">Zurück</a>
        </footer>
    </div>
{% endblock %}

ppServer/backend/levelUp/templates/levelUp/personal.html
{% extends 'base/headed_main.html' %}
{% load static crispy_forms_tags %}
{% block extra-head %}
<link rel="stylesheet" href="{% static 'auth/css/centered_form.css' %}">
<style>
legend { margin-top: 1em; }
textarea { width: 100%; }
</style>
{% endblock %}
{% block main %}
<form class='form' id="personal-form" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    {% crispy form %}

    <div class="d-flex gap-3 mt-2 mb-5">
        <a class="btn btn-outline-light" href="{% url 'wiki:religion_add' %}?next={{ request.path|urlencode }}">neue Religion</a>
        <a class="btn btn-outline-light" href="{% url 'wiki:beruf_add' %}?next={{ request.path|urlencode }}">neuer Beruf</a>
    </div>
</form>

<div class="fixed-bottom">
    <footer class="sticky-footer d-flex justify-content-center">
        <button type="submit" class="btn btn-primary" form="personal-form">Speichern</button>
        <a class="btn btn-outline-primary mx-2" href="{{ back_url }}">Zurück</a>
    </footer>
</div>
{% endblock %}