ppServer/backend/combat/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'combat'

urlpatterns = [
	path('', views.RegionSelectView.as_view(), name='region_select'),
	path('region_editor/<int:pk>/', views.RegionEditorView.as_view(), name='region_editor'),
	path('fight/<int:pk>/', views.FightView.as_view(), name='fight'),
]

ppServer/backend/crafting/urls.py
from django.urls import path

from . import views
from .api_views import GetMinecraftRecipesView

app_name = 'crafting'

urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('inventory/', views.InventoryView.as_view(), name='inventory'),
	path('craft/', views.CraftingView.as_view(), name='craft'),
	path('details/<int:pk>/', views.RecipeDetailsView.as_view(), name='details'),
	path('sp_give_items/', views.SpGiveItemsView.as_view(), name='sp_give_items'),
	path('regions/', views.RegionListView.as_view(), name='regions'),
	path('mining/<int:pk>/', views.MiningView.as_view(), name='mining'),

	path('api/mc_recipes/', GetMinecraftRecipesView.as_view(), name='api_mc_recipes'),
]

ppServer/backend/dex/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView

from ppServer.decorators import verified_account

from . import views

app_name = 'dex'

urlpatterns = [
    path('', verified_account(TemplateView.as_view(template_name="dex/index.html")), name='index'),

    path('monster/', include('dex.monster.urls')),

    path('geschöpf/', views.GeschöpfIndexView.as_view(), name='geschöpf_index'),
    path('geschöpf/<int:pk>', views.GeschöpfDetailView.as_view(), name='geschöpf_detail'),

    path('para_pflanze/', views.ParaPflanzeIndexView.as_view(), name='para_pflanze_index'),
    path('para_pflanze/<int:pk>', views.ParaPflanzeDetailView.as_view(), name='para_pflanze_detail'),

    path('para_tier/', views.ParaTierIndexView.as_view(), name='para_tier_index'),
    path('para_tier/<int:pk>', views.ParaTierDetailView.as_view(), name='para_tier_detail'),
]

ppServer/backend/ppServer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView, RedirectView
from django.urls import include, path

from debug_toolbar.toolbar import debug_toolbar_urls


class LegalActUpdateRedirectView(RedirectView):
    permanent = True
    query_string = True
    pattern_name = "politics:admin-vote-on-legalAct"

    def get_redirect_url(self, *args, **kwargs):
        url = super().get_redirect_url(kwargs["pk"])
        return url

urlpatterns = [
    # custom admin-update view
    path('admin/politics/legalact/<int:pk>/change/', LegalActUpdateRedirectView.as_view()),

    path('admin/', admin.site.urls),
    path('auth/', include('auth_custom.urls')),
    path('accounts/', include('auth_custom.urls')),

    path('cards/', include('cards.urls')),
    path('changelog/', include('changelog.urls')),
    path('character/campaign/', include('campaign.urls')),
    path('character/export/', include('characterExport.urls')),
    path('character/', include('character.urls')),
    path('chat/', include('chat.urls')),
    path('combat/', include('combat.urls')),
    path('crafting/', include('crafting.urls')),
    path('create/', include('create.urls')),
    path('dex/', include('dex.urls')),
    path('file/', include('fileserver.urls')),
    path('chat2.0/', include('httpChat.urls')),
    path('lerneinheiten/', include('lerneinheiten.urls')),
    path('levelUp/', include('levelUp.urls')),
    path('log/', include('log.urls')),
    path('news/', include('news.urls')),
    path('planner/', include('planner.urls')),
    path('politics/', include('politics.urls')),
    path('polls/', include('polls.urls')),
    path('quiz/', include('quiz.urls')),
    path('service/', include('service.urls')),
    path('shop/', include('shop.urls')),
    path('time_space/', include('time_space.urls')),
    path('todo/', include('todo.urls')),
    path('web_push/', include('webPush.urls')),
    path('wiki/', include('wiki.urls')),

    path('robots.txt', TemplateView.as_view(template_name="base/robots.txt")),
    path('sw.js', TemplateView.as_view(template_name="webPush/service_worker.js", content_type='application/javascript'), name='sw.js'),
    path("prometheus/", include("django_prometheus.urls")),

    path('', include("base.urls")),
]

handler404 = TemplateView.as_view(template_name='base/error_404.html')

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

ppServer/backend/shop/urls.py
from django.urls import path, register_converter

from .converter import *
from .views.index import index, review_items, transfer_items, propose_item, shopmodel_list
from .views.buy import BuyView
from .views import list as listViews

app_name = 'shop'
register_converter(get_ModelNameConverter(app_name, shopmodel_list), "model")
register_converter(get_ModelNameConverter(app_name, [m for m in shopmodel_list if m._meta.model_name != "tinker"]), "buyable_model")

urlpatterns = [
    path('', index, name='index'),
    path('review/', review_items, name='review_items'),
    path('transfer-items/', transfer_items, name='transfer_items'),
    path('propose/<model:model>/', propose_item, name="propose"),

    path('all/', listViews.FullShopTableView.as_view(), name='all'),

    path('items/', listViews.ItemTableView.as_view(), name='item_list'),
    path('waffen_werkzeuge/', listViews.WaffenWerkzeugeTableView.as_view(), name='waffen_werkzeuge_list'),
    path('magazine/', listViews.MagazinTableView.as_view(), name='magazin_list'),
    path('pfeile_bolzen/', listViews.PfeilBolzenTableView.as_view(), name='pfeil_bolzen_list'),
    path("schusswaffen", listViews.SchusswaffenTableView.as_view(), name='schusswaffen_list'),
    path('magische_ausrüstung/', listViews.MagischeAusrüstungTableView.as_view(), name='magische_ausrüstung_list'),
    path('rituale_runen/', listViews.RitualeRunenTableView.as_view(), name='rituale_runen_list'),
    path('rüstungen/', listViews.RüstungTableView.as_view(), name='rüstung_list'),
    path('ausruestung_technik/', listViews.AusrüstungTechnikTableView.as_view(), name='ausrüstung_technik_list'),
    path('fahrzeuge/', listViews.FahrzeugTableView.as_view(), name='fahrzeug_list'),
    path('einbauten/', listViews.EinbautenTableView.as_view(), name='einbauten_list'),
    path('zauber/', listViews.ZauberTableView.as_view(), name='zauber_list'),
    path('alchemie/', listViews.AlchemieTableView.as_view(), name='alchemie_list'),
    path('tinker/', listViews.TinkerTableView.as_view(), name='tinker_list'),
    path('begleiter/', listViews.BegleiterTableView.as_view(), name='begleiter_list'),
    path('engelsroboter/', listViews.EngelsroboterTableView.as_view(), name='engelsroboter_list'),

    path('buy_<buyable_model:model>/<int:id>/', BuyView.as_view(), name="buy"),
]

ppServer/backend/crafting/models.py
from datetime import timedelta

from django.db import models, transaction
from django.db.models import Subquery, OuterRef, F, Case, When
from django.core.validators import MinValueValidator, MaxValueValidator

from django_resized import ResizedImageField

from character.models import Spieler, Spezialfertigkeit, Wissensfertigkeit, Charakter
from shop.models import Tinker


############### Profiles & Inventory #################

class RunningRealtimeRecipe(models.Model):
	class Meta:
		ordering = ["profil", "finishes_at", "recipe", "num"]

	recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE)
	profil = models.ForeignKey("Profile", on_delete=models.CASCADE)

	num = models.PositiveIntegerField(validators=[MinValueValidator(1)])
	starts_at = models.DateTimeField(auto_now_add=True)
	begins_at = models.DateTimeField()
	finishes_at = models.DateTimeField()

	lock = models.TextField(null=True, blank=True)

	def distribute_products_and_stop(self) -> list["InventoryItem"]:
		""" gives recipe's productsto Profile and deletes itself. Returns newly created InventoryItems (e.g. to decide if there was a table added) """

		with transaction.atomic():

			# update existing iitems
			InventoryItem.objects\
				.filter(char=self.profil, item__in=self.recipe.product_set.values_list("item_id", flat=True))\
				.annotate(add = Subquery(Product.objects.filter(recipe=self.recipe, item=OuterRef("item")).values_list("num", flat=True)))\
				.update(num=F("num") + (F("add") * self.num))
			
			# create new iitems
			new_iitems = [InventoryItem(item=product.item, num=product.num*self.num, char=self.profil) for product in self.recipe.product_set.exclude(item__in=InventoryItem.objects.filter(char=self.profil).values_list("item_id", flat=True))]
			if new_iitems: InventoryItem.objects.bulk_create(new_iitems)

			# end realtime execution of recipe
			self.delete()

			return new_iitems

class RelCrafting(models.Model):
	class Meta:
		ordering = ["spieler"]

		verbose_name = "Crafting von Spieler"
		verbose_name_plural = "Crafting von Spielern"

	spieler = models.OneToOneField(Spieler, on_delete=models.CASCADE)
	profil = models.ForeignKey("Profile", on_delete=models.SET_NULL, null=True, blank=True)

	char = models.ForeignKey(Charakter, on_delete=models.SET_NULL, null=True, blank=True)
	favorite_recipes = models.ManyToManyField("Recipe")

	def __str__(self):
		return "{} aktiv mit {}".format(self.spieler.__str__() if self.spieler else "-", self.profil.name if self.profil else "-")


class Profile(models.Model):
	class Meta:
		ordering = ["name"]
		verbose_name = "Profil"
		verbose_name_plural = "Profile"

	owner = models.ForeignKey(Spieler, on_delete=models.SET_NULL, null=True)
	name = models.CharField(max_length=100, unique=True)

	miningTime = models.DurationField('mining time (hh:mm:ss)', null=True, blank=True, default=timedelta(minutes=0))
	craftingTime = models.DurationField('crafting time (hh:mm:ss)', null=True, blank=True, default=timedelta(minutes=0))
	tableOrdering = models.JSONField(default=list)

	electricity = models.FloatField(default=0.0)
	thermic = models.FloatField(default=0.0)
	woobles = models.FloatField(default=0.0, validators=[MinValueValidator(0.0)])

	restricted = models.BooleanField(default=False)

	def __str__(self):
		return self.name


	def getTables(self, iitem_ids: list[int], tinker_id=None) -> list[dict["id", "name", "icon"]]:

		# get tables
		rawTables = Table.objects.prefetch_related("item", "part")\
			.annotate(
				used = Subquery(ProfileTableDurability.objects.filter(char=self, table=OuterRef("pk")).values_list("recipes_crafted", flat=True)),
				durability_left = F("durability") - F("used"),
				percent_durability_left = Case(When(durability=0, then=0), default=100 * (F("durability") - F("used")) / F("durability") +0.5, output_field=models.IntegerField())
			)\
			.order_by("item__name")
		if tinker_id is not None: rawTables = rawTables.filter(item__id=tinker_id)

		tables = [Recipe.getHandwerk()]
		for t in rawTables:
			tables.append({
				"id": t.item.id, "name": t.item.name, "icon": t.item.getIconUrl(),
				"percent_durability_left": t.percent_durability_left,
				"durability_left": t.durability_left,
				"part": t.part.toDict() if t.part else None,
				"owns_part": t.part.id in iitem_ids if t.part else False,
			})

		if tinker_id is not None: return tables[-1]

		# get & use order
		order = self.tableOrdering
		ordered_tables = []

		# default alphabetical ordering but beginning with Handwerk
		if not order: return tables

		# sort by ids of ordering
		for o in order:
			table = next((t for t in tables if t["id"] == o), None)

			# skip over in case a table is removed after saving ordering to db
			if table is None: continue

			# append tables in order
			ordered_tables.append(table)

		# return custom ordered + rest
		return ordered_tables + [t for t in tables if t not in ordered_tables]


class InventoryItem(models.Model):

	class Meta:
		ordering = ["char", "item"]
		unique_together = ("char", "item")

		verbose_name = "Inventar Item"
		verbose_name_plural = "Inventar Items"

	char = models.ForeignKey(Profile, on_delete=models.CASCADE)
	item = models.ForeignKey(Tinker, on_delete=models.CASCADE)

	num = models.FloatField(default=0, validators=[MinValueValidator(0)])

	def __str__(self):
		return "{}x {} von {}".format(self.num, self.item.name, self.char.name)



############### Recipes #################

class Ingredient(models.Model):

	class Meta:
		verbose_name = "Zutat"
		verbose_name_plural = "Zutaten"

	num = models.FloatField(default=1.0, validators=[MinValueValidator(0)])

	item = models.ForeignKey(Tinker, on_delete=models.CASCADE, related_name="ingredient", related_query_name="ingredient")
	recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE)

	def __str__(self):
		return "Rezept {} benötigt {}x {}".format(self.recipe.id, self.num, self.item)


class Product(models.Model):

	class Meta:
		verbose_name = "Produkt"
		verbose_name_plural = "Produkte"

	num = models.FloatField(default=1.0, validators=[MinValueValidator(0)])

	item = models.ForeignKey(Tinker, on_delete=models.CASCADE, related_name="prod", related_query_name="prod")
	recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE)

	def __str__(self):
		return "Rezept {} produziert {}x {}".format(self.recipe.id, self.num, self.item)

class Table(models.Model):
	class Meta:
		verbose_name = "Werkstätte"
		verbose_name_plural = "Werkstätten"

		ordering = ("item", "part")

	durability = models.PositiveSmallIntegerField(default=0, help_text="in #Rezepte")
	part = models.ForeignKey(Tinker, on_delete=models.SET_NULL, null=True, blank=True, related_name="part")

	item = models.ForeignKey(Tinker, on_delete=models.CASCADE)

	def __str__(self):
		return "Werkstätte {}".format(self.item)

class ProfileTableDurability(models.Model):
	class Meta:
		ordering = ["char", "table"]
		unique_together = ("char", "table")

	table = models.ForeignKey(Table, on_delete=models.CASCADE)
	char = models.ForeignKey(Profile, on_delete=models.CASCADE)

	recipes_crafted = models.PositiveIntegerField(default=0)	# max:table.duration. At that point broken until new part added and set to 0


class Recipe(models.Model):

	class Meta:
		verbose_name = "Rezept"
		verbose_name_plural = "Rezepte"

	table = models.ForeignKey(Table, on_delete=models.CASCADE, null=True, blank=True)
	duration = models.DurationField('herstellungsdauer (hh:mm:ss)', default=timedelta(seconds=0), null=True, blank=True)

	spezial = models.ManyToManyField(Spezialfertigkeit, blank=True)
	wissen = models.ManyToManyField(Wissensfertigkeit, blank=True)

	def __str__(self):
		return "Rezept für {} an {}".format([p for p in self.product_set.all()], self.table)

	# to display a table in /crafting for all recipes without an actual table
	@staticmethod
	def getHandwerk():
		return {"name": "Handwerk", "icon": "/static/crafting/img/Handwerk.png", "id": 0, "available": True, "link": None}


############### Mining #################

class ToolType(models.Model):

	class Meta:
		verbose_name = "Tool Type"
		verbose_name_plural = "Tool Types"
		ordering = ["name"]

	name = models.CharField(max_length=64, unique=True)

	def __str__(self):
		return f"ToolType {self.name}"

class Region(models.Model):

	class Meta:
		verbose_name = "Region"
		verbose_name_plural = "Regionen"

		ordering = ["wooble_cost", "name"]

	icon = ResizedImageField(size=[64, 64])
	name = models.CharField(max_length=64, unique=True)
	wooble_cost = models.FloatField(default=0.0, validators=[MinValueValidator(0.0)])
	permanently_needs = models.ManyToManyField(Tinker, blank=True)

	allowed_profiles = models.ManyToManyField(Profile, blank=True)

	def __str__(self):
		return "Region {}".format(self.name)



class BlockChance(models.Model):
	class Meta:
		verbose_name = "Block Chance"
		verbose_name_plural = "Block Chances"
		ordering = ["-chance"]

	region = models.ForeignKey(Region, on_delete=models.CASCADE)
	block = models.ForeignKey("Block", on_delete=models.CASCADE)

	chance = models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(1)], help_text="Higher is appears more often. # copies goes into a pool to randomly select the next block.")

class Drop(models.Model):
	class Meta:
		verbose_name = "Block Drop"
		verbose_name_plural = "Block Drops"
		ordering = ["-chance"]
	
	item = models.ForeignKey(Tinker, on_delete=models.CASCADE)
	block = models.ForeignKey("Block", on_delete=models.CASCADE)

	chance = models.FloatField(default=50, validators=[MinValueValidator(0.0), MaxValueValidator(100.0)], help_text="Probabiliy of (0%, 100%]")

	def toDict(self):
		return {
			"chance": self.chance,
			"item": self.item.toDict(),
		}

class Block(models.Model):

	class Meta:
		verbose_name = "Block"
		verbose_name_plural = "Blöcke"

	icon = ResizedImageField(size=[64, 64])
	name = models.CharField(max_length=64, unique=True)

	hardness = models.PositiveIntegerField(default=1)

ppServer/backend/crafting/forms.py
from django import forms

from crispy_forms.layout import Layout, Div, Field

from base.crispy_form_decorator import crispy
from shop.models import Tinker

@crispy(form_tag=False)
class AddToInventoryForm(forms.Form):
    amount = forms.IntegerField(min_value=1, initial=1, label="Anzahl", required=True)
    item = forms.ModelChoiceField(Tinker.objects.order_by("name"), label="Item")

    def get_layout(self):
        return Layout(
            Div(
                Field('amount', wrapper_class='col-12 col-sm'),
                Field('item', wrapper_class='col-12 col-sm'),
            css_class='row'),
        )

ppServer/backend/crafting/templates/crafting/craft.html
{% extends 'base/headed_main.html' %}
{% load static l10n %}
{% block extra-head %}
<link rel="stylesheet"  type="text/css" href="{% static 'crafting/css/craft.css' %}">
<script src="{% static 'res/js/axios.min.js' %}" type='text/javascript'></script>
<script src="{% static 'base/js/ajax.js' %}"></script>
<script src="{% static 'crafting/js/craft.js' %}"></script>
<script src="{% static 'res/js/sortable@1.15.2.min.js' %}" defer></script>
{% endblock %}

{% block asides %}
  <div class="toast-container m-2"></div>

  <b id="running-recipes-label">laufende Rezepte:</b>
  <ul class="running-recipes-list m-2" aria-labelledby="running-recipes-label"></ul>

  <hr class="my-5 d-none">
{% endblock %}

{% block main %}
<aside class="tables"></aside>

<header class="head">
	<div class="search input-with-btn">
		<input type="text" list="item-search" id="search-input" class="p-1" oninput="update_search_itemname_options(event)" />
		<datalist id="item-search"></datalist>

		<button onclick="search()" id="search-btn" class="btn btn-primary">Suche</button>
	</div>

	<div class="btns">
		<a href="{% url 'crafting:inventory' %}">Inventar</a>
		<a href="{% url 'crafting:regions' %}">Ressourcen sammeln</a>
		<a class="mt-4" href="{% url 'crafting:index' %}?redirect={{ request.path|urlencode }}">Profil wechseln</a>

		{% if perms.character.is_Spielleitung %}
			<a href="{% url 'crafting:sp_give_items' %}">Profilen Items geben</a>
		{% endif %}
	</div>
</header>


<section class="recipes"></section>
{% endblock %}

ppServer/backend/crafting/templates/crafting/details.html
{% extends 'base/headed_main.html' %}
{% load static l10n crafting.duration %}
{% block extra-head %}
<link rel="stylesheet" type="text/css" href="{% static 'crafting/css/details.css' %}">
{% endblock %}

{% block main %}
<div class="nav d-flex justify-content-between">
	<a href="{% url 'crafting:inventory' %}" class="text-light">Inventar</a>
	<a href="{% url 'crafting:regions' %}" class="text-light">Ressourcen sammeln</a>
	<a href="{% url 'crafting:craft' %}" class="text-light">Crafting</a>
	<a href="{% url 'crafting:index' %}?redirect={{ request.path|urlencode }}" class="text-light">Profil wechseln</a>
</div>

<div class="overlay d-block">
	<label for="overlay__duration">Crafting Time:</label><span id="overlay__duration">{{ object.duration|duration }}</span>
	<label for="overlay__spezial">Spezialfertigkeiten:</label><div id="overlay__spezial">{{ object.spezial_names|default:"-" }}</div>
	<label for="overlay__wissen">Wissensfertigkeiten:</label><div id="overlay__wissen">{{ object.wissen_names|default:"-" }}</div>
	<label for="overlay__table">Zutaten:</label><div id="overlay__ingredients">
		{% for ingredient in object.ingredient_set.all %}
			<a class="ingredient" href="{% url 'shop:tinker_list' %}?name__icontains={{ ingredient.item.name|urlencode }}">
				<img src="{{ ingredient.item.icon.url }}" alt="{{ ingredient.item.name }}">
				<span class="num">{{ ingredient.num|floatformat:-1 }}</span>
				<span class="name">{{ ingredient.item.name }}</span>
			</a>
		{% empty %}<div>-</div>
		{% endfor %}
	</div>
	<label for="overlay__table">Hergestellt an:</label><div id="overlay__table">
		{% if object.table %}
		<a class="ingredient" href="{% url 'shop:tinker_list' %}?name__icontains={{ object.table.item.name|urlencode }}">
			<img src="{{ object.table.item.icon.url }}" alt="{{ object.table.item.name }}">
			<span class="name">{{ object.table.item.name }}</span>
		</a>
		{% else %}
		<div class="ingredient">
			<img src="{{ handwerk.icon }}" alt="{{ handwerk.name }}">
			<span class="name">{{ handwerk.name }}</span>
		</div>
		{% endif %}
	</div>
	<label for="overlay__table">Produkte:</label><div id="overlay__table">
		{% for product in object.product_set.all %}
			<a class="ingredient" href="{% url 'shop:tinker_list' %}?name__icontains={{ product.item.name|urlencode }}">
				<img src="{{ product.item.icon.url }}" alt="{{ product.item.name }}">
				<span class="num">{{ product.num|floatformat:-1 }}</span>
				<span class="name">{{ product.item.name }}</span>
			</a>
		{% empty %}<div>-</div>
		{% endfor %}
	</div>
</div>

<button class="btn btn-lg btn-primary mt-3" onclick="window.history.back()">Zurück</button>
{% endblock %}

ppServer/backend/crafting/templates/crafting/regions.html
{% extends 'base/headed_main.html' %}
{% load static l10n crafting.dict_key %}

{% block extra-head %}
<link rel="stylesheet"  type="text/css" href="{% static 'crafting/css/inventory.css' %}">
{% endblock %}

{% block main %}
<div class="head">
	<div class="btns">
		<a class="mt-4" href="{% url 'crafting:inventory' %}">Inventar</a>
		<a href="{% url 'crafting:craft' %}">Crafting</a>
		<a class="mt-4" href="{% url 'crafting:index' %}?redirect={{ request.path|urlencode }}">Profil wechseln</a>

		{% if perms.character.is_Spielleitung %}
		<div></div>
		<a href="{% url 'crafting:sp_give_items' %}">Profilen Items geben</a>
		{% endif %}
	</div>
</div>

<h2>Wo willst du abbauen?</h2>

<p class="text-danger">aktuelle Woobles: {{ profil.woobles|floatformat }}</p>

<ul class="list-group">
    {% for region in object_list %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        {% if region.accessible and region.has_items == region.needs_items %}
        <a href="{% url 'crafting:mining' region.pk %}" class="text-dark d-flex flex-wrap align-items-center justify-content-between w-100">

            <div>
                <img src="{{ region.icon.url }}" class="rounded-circle border border-primary" style="height: 50px; aspect-ratio: 1" loading="lazy">
                <span class="mx-2 fw-bold">{{ region.name }}</span>
            </div>
            <span>
            {% for item in drops|dict_key:region.pk %}
                <img class="drop" src="{{ item.icon.url }}" alt="{{ item.name }}" style="height: 27px; aspect-ratio: 1;" loading="lazy">
            {% endfor %}
            </span>
        </a>
        {% else %}
        <form method="post" id="region-form--{{ region.pk }}" class="bg-medium text-dark d-flex flex-wrap align-items-center justify-content-between w-100">
            {% csrf_token %}
            <input type="number" value="{{ region.pk }}" name="region_id" hidden>
            <div>
                <img src="{{ region.icon.url }}" class="rounded-circle border border-primary" style="height: 50px; aspect-ratio: 1" loading="lazy">
                <span class="mx-2 fw-bold">{{ region.name }}</span>
            </div>
            
            {% if region.needs_items and region.has_items != region.needs_items %}
            <span>
                <span class="text-danger d-block">Fehlende Items, Zugang benötigt:</span>
                {% for item in region.permanently_needs.all %}
                    <img class="drop" src="{{ item.icon.url }}" alt="{{ item.name }}" style="height: 27px; aspect-ratio: 1;" title="{{ item.name }}" loading="lazy">
                {% endfor %}
            </span>
            {% endif %}

            <span>
                {% for item in drops|dict_key:region.pk %}
                <img class="drop" src="{{ item.icon.url }}" alt="{{ item.name }}" style="height: 27px; aspect-ratio: 1;" title="{{ item.name }}" loading="lazy">
                {% endfor %}
            </span>
        </form>
        {% if not region.accessible %}
        <p><button type="submit" form="region-form--{{ region.pk }}" class="btn btn-dark btn-sm">Zugang kaufen <span class="text-danger">{{ region.wooble_cost }}</span></button></p>
        {% endif %}
    {% endif %}
    </li>
    {% empty %}
    <p>Es gibt (noch) keine Regionen, die du mit deiner Zerstörungswut heimsuchen könntest.</p>
    <a class="text-light" href="{% url 'crafting:index' %}?redirect={{ request.path|urlencode }}">Profil wechseln</a>
    {% endfor %}
</ul>

<h2 class="mt-5">
    Wo willst du kämpfen?
    {% if perms.character.is_Spielleitung %}<a class="btn btn-primary" href="{% url 'combat:region_select' %}">Bearbeiten</a>{% endif %}
</h2>

<ul class="list-group">
    {% for region in combat_regions %}
	<li class="list-group-item">
        <a href="{% url 'combat:fight' region.id %}" class="text-dark d-flex flex-wrap align-items-center justify-content-between w-100">

            <div>
                <img src="{% static 'res/img/goren_logo.svg' %}" class="rounded-circle border border-primary" style="height: 50px; aspect-ratio: 1" loading="lazy">
                <span class="mx-2 fw-bold">{{ region.name }}</span>
            </div>
            <span>
                {% for item in region.enemies.all %}
                <img class="drop" src="{{ item.sprite.url }}" alt="{{ item.name }}" style="height: 27px; aspect-ratio: 1;" title="{{ item.name }}" loading="lazy">
                {% endfor %}
            </span>
        </a>
	</li>
    {% empty %}
    <p>Keine Regionen vorhanden</p>
	{% endfor %}
</ul>
{% endblock %}